### ISSUE TITLE
Plugin does not work for json files

### ISSUE THREAD

**Issue by vad3x** [slune-org/ts-transform-auto-require#3]
The plugin does not work as expected when glob points to json files.

It seems this line (removing file extension) is making incorrect `require`s (points to nothing):

https://github.com/slune-org/ts-transform-auto-require/blob/master/src/FileAnalyzer.ts#L52

Generated result:
```js
{
  "json-file": require("./json-file").default,
  ...
}
```

Expected result:

```js
{
  "json-file.json": require("./json-file.json").default,
  ...
}
```

It seems like file extension trimming suppose to be configurable.

**Comment by sveyret** [comment]
Hi @vad3x,
Thank you for submitting the ticket. File extensions are indeed removed, as stated in the README file, so this is not really an issue.
Anyway, you probably are not the only one which would like to require some other kind of file, so making the trimming configurable, as you suggested, is a good idea. I will try to work on this during the following days, even if I have very little time those days. If you don’t see any change in a week, please feel free to provide a PR!

**Comment by sveyret** [comment]
It has taken a bit more time than expected… :wink: 

But the new version 1.3.0 is now taking care of JSON files. Thanks to a new configuration variable `target.codeExtensions` you can decide the way a file is treated, depending on its extension.
